/**
 * 🎧 英语听写词库 — 200个高频词
 * 按领域分类，支持难度筛选
 */
export interface DictationWord {
  id: string;
  word: string;
  phonetic: string;
  chinese: string;
  sentence?: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  domain: string;
}

export const dictationWords: DictationWord[] = [
  // ── 基础词汇（初中） ──
  { id: 'w001', word: 'apple',       phonetic: '/ˈæpl/',        chinese: '苹果',       sentence: 'I eat an apple every day.', difficulty: 1, domain: '基础词汇' },
  { id: 'w002', word: 'book',        phonetic: '/bʊk/',         chinese: '书',         sentence: 'This is my favorite book.', difficulty: 1, domain: '基础词汇' },
  { id: 'w003', word: 'cat',         phonetic: '/kæt/',         chinese: '猫',         sentence: 'The cat is sleeping.', difficulty: 1, domain: '基础词汇' },
  { id: 'w004', word: 'dog',         phonetic: '/dɒɡ/',         chinese: '狗',         sentence: 'I have a pet dog.', difficulty: 1, domain: '基础词汇' },
  { id: 'w005', word: 'fish',        phonetic: '/fɪʃ/',         chinese: '鱼',         sentence: 'There are many fish in the river.', difficulty: 1, domain: '基础词汇' },
  { id: 'w006', word: 'girl',        phonetic: '/ɡɜːrl/',       chinese: '女孩',       sentence: 'The girl is reading a book.', difficulty: 1, domain: '基础词汇' },
  { id: 'w007', word: 'happy',       phonetic: '/ˈhæpi/',       chinese: '快乐的',     sentence: 'She looks very happy.', difficulty: 1, domain: '基础词汇' },
  { id: 'w008', word: 'jump',        phonetic: '/dʒʌmp/',        chinese: '跳',         sentence: 'The rabbit can jump high.', difficulty: 1, domain: '基础词汇' },
  { id: 'w009', word: 'king',        phonetic: '/kɪŋ/',          chinese: '国王',       sentence: 'The king lives in a castle.', difficulty: 1, domain: '基础词汇' },
  { id: 'w010', word: 'lamp',        phonetic: '/læmp/',         chinese: '灯',         sentence: 'Turn on the lamp, please.', difficulty: 1, domain: '基础词汇' },
  { id: 'w011', word: 'milk',        phonetic: '/mɪlk/',         chinese: '牛奶',       sentence: 'I drink milk every morning.', difficulty: 1, domain: '基础词汇' },
  { id: 'w012', word: 'name',        phonetic: '/neɪm/',         chinese: '名字',       sentence: 'What is your name?', difficulty: 1, domain: '基础词汇' },
  { id: 'w013', word: 'orange',      phonetic: '/ˈɒrɪndʒ/',      chinese: '橙子',       sentence: 'Oranges are rich in vitamin C.', difficulty: 1, domain: '基础词汇' },
  { id: 'w014', word: 'pencil',      phonetic: '/ˈpensl/',       chinese: '铅笔',       sentence: 'Write with a pencil.', difficulty: 1, domain: '基础词汇' },
  { id: 'w015', word: 'queen',       phonetic: '/kwiːn/',        chinese: '女王',       sentence: 'The queen wore a crown.', difficulty: 1, domain: '基础词汇' },
  { id: 'w016', word: 'river',       phonetic: '/ˈrɪvər/',       chinese: '河流',       sentence: 'The river flows to the sea.', difficulty: 1, domain: '基础词汇' },
  { id: 'w017', word: 'sunny',       phonetic: '/ˈsʌni/',        chinese: '晴朗的',     sentence: 'It is a sunny day.', difficulty: 1, domain: '基础词汇' },
  { id: 'w018', word: 'table',       phonetic: '/ˈteɪbl/',       chinese: '桌子',       sentence: 'Put it on the table.', difficulty: 1, domain: '基础词汇' },
  { id: 'w019', word: 'umbrella',    phonetic: '/ʌmˈbrelə/',     chinese: '雨伞',       sentence: 'Take an umbrella, it might rain.', difficulty: 1, domain: '基础词汇' },
  { id: 'w020', word: 'water',       phonetic: '/ˈwɔːtər/',      chinese: '水',         sentence: 'I need a glass of water.', difficulty: 1, domain: '基础词汇' },

  // ── 常用动词 ──
  { id: 'w021', word: 'begin',       phonetic: '/bɪˈɡɪn/',       chinese: '开始',       sentence: 'Let us begin the class.', difficulty: 2, domain: '常用动词' },
  { id: 'w022', word: 'choose',      phonetic: '/tʃuːz/',        chinese: '选择',       sentence: 'You need to choose one.', difficulty: 2, domain: '常用动词' },
  { id: 'w023', word: 'decide',      phonetic: '/dɪˈsaɪd/',      chinese: '决定',       sentence: 'I decided to study harder.', difficulty: 2, domain: '常用动词' },
  { id: 'w024', word: 'enjoy',       phonetic: '/ɪnˈdʒɔɪ/',      chinese: '享受',       sentence: 'I enjoy reading books.', difficulty: 2, domain: '常用动词' },
  { id: 'w025', word: 'follow',      phonetic: '/ˈfɒloʊ/',       chinese: '跟随',       sentence: 'Follow me, please.', difficulty: 2, domain: '常用动词' },
  { id: 'w026', word: 'finish',      phonetic: '/ˈfɪnɪʃ/',       chinese: '完成',       sentence: 'I finished my homework.', difficulty: 2, domain: '常用动词' },
  { id: 'w027', word: 'happen',      phonetic: '/ˈhæpən/',       chinese: '发生',       sentence: 'What happened yesterday?', difficulty: 2, domain: '常用动词' },
  { id: 'w028', word: 'imagine',     phonetic: '/ɪˈmædʒɪn/',     chinese: '想象',       sentence: 'Imagine a world without war.', difficulty: 3, domain: '常用动词' },
  { id: 'w029', word: 'improve',     phonetic: '/ɪmˈpruːv/',     chinese: '提高',       sentence: 'Practice helps improve your skills.', difficulty: 2, domain: '常用动词' },
  { id: 'w030', word: 'invite',      phonetic: '/ɪnˈvaɪt/',      chinese: '邀请',       sentence: 'I invited her to the party.', difficulty: 2, domain: '常用动词' },
  { id: 'w031', word: 'mention',     phonetic: '/ˈmenʃn/',       chinese: '提及',       sentence: 'He mentioned your name.', difficulty: 3, domain: '常用动词' },
  { id: 'w032', word: 'notice',      phonetic: '/ˈnoʊtɪs/',      chinese: '注意到',     sentence: 'Did you notice the change?', difficulty: 2, domain: '常用动词' },
  { id: 'w033', word: 'offer',       phonetic: '/ˈɒfər/',        chinese: '提供',       sentence: 'He offered me a job.', difficulty: 2, domain: '常用动词' },
  { id: 'w034', word: 'prepare',     phonetic: '/prɪˈper/',      chinese: '准备',       sentence: 'I need to prepare for the exam.', difficulty: 2, domain: '常用动词' },
  { id: 'w035', word: 'receive',     phonetic: '/rɪˈsiːv/',      chinese: '收到',       sentence: 'I received your letter.', difficulty: 2, domain: '常用动词' },
  { id: 'w036', word: 'remember',    phonetic: '/rɪˈmembər/',    chinese: '记住',       sentence: 'Remember to lock the door.', difficulty: 2, domain: '常用动词' },
  { id: 'w037', word: 'suggest',     phonetic: '/səˈdʒest/',     chinese: '建议',       sentence: 'I suggest you try again.', difficulty: 3, domain: '常用动词' },
  { id: 'w038', word: 'support',     phonetic: '/səˈpɔːrt/',     chinese: '支持',       sentence: 'My family supports me.', difficulty: 2, domain: '常用动词' },
  { id: 'w039', word: 'wonder',      phonetic: '/ˈwʌndər/',      chinese: '想知道',     sentence: 'I wonder what will happen.', difficulty: 2, domain: '常用动词' },
  { id: 'w040', word: 'achieve',     phonetic: '/əˈtʃiːv/',      chinese: '实现',       sentence: 'She achieved her goal.', difficulty: 3, domain: '常用动词' },

  // ── 形容词 ──
  { id: 'w041', word: 'beautiful',   phonetic: '/ˈbjuːtɪfl/',    chinese: '美丽的',     sentence: 'The sunset is beautiful.', difficulty: 2, domain: '常用形容词' },
  { id: 'w042', word: 'careful',     phonetic: '/ˈkerfl/',       chinese: '小心的',     sentence: 'Be careful when crossing the road.', difficulty: 2, domain: '常用形容词' },
  { id: 'w043', word: 'dangerous',   phonetic: '/ˈdeɪndʒərəs/',  chinese: '危险的',     sentence: 'This road is dangerous.', difficulty: 3, domain: '常用形容词' },
  { id: 'w044', word: 'difficult',   phonetic: '/ˈdɪfɪkəlt/',   chinese: '困难的',     sentence: 'The exam was difficult.', difficulty: 2, domain: '常用形容词' },
  { id: 'w045', word: 'excellent',   phonetic: '/ˈeksələnt/',    chinese: '优秀的',     sentence: 'You did an excellent job!', difficulty: 3, domain: '常用形容词' },
  { id: 'w046', word: 'famous',      phonetic: '/ˈfeɪməs/',      chinese: '著名的',     sentence: 'This city is famous for its food.', difficulty: 2, domain: '常用形容词' },
  { id: 'w047', word: 'generous',    phonetic: '/ˈdʒenərəs/',    chinese: '慷慨的',     sentence: 'He is a generous person.', difficulty: 3, domain: '常用形容词' },
  { id: 'w048', word: 'honest',      phonetic: '/ˈɒnɪst/',       chinese: '诚实的',     sentence: 'Always be honest.', difficulty: 2, domain: '常用形容词' },
  { id: 'w049', word: 'important',   phonetic: '/ɪmˈpɔːrtnt/',   chinese: '重要的',     sentence: 'Education is important.', difficulty: 2, domain: '常用形容词' },
  { id: 'w050', word: 'interesting', phonetic: '/ˈɪntrəstɪŋ/',   chinese: '有趣的',     sentence: 'This book is very interesting.', difficulty: 2, domain: '常用形容词' },
  { id: 'w051', word: 'necessary',   phonetic: '/ˈnesəseri/',    chinese: '必要的',     sentence: 'Water is necessary for life.', difficulty: 3, domain: '常用形容词' },
  { id: 'w052', word: 'popular',     phonetic: '/ˈpɑːpjələr/',   chinese: '流行的',     sentence: 'This song is very popular.', difficulty: 2, domain: '常用形容词' },
  { id: 'w053', word: 'possible',    phonetic: '/ˈpɑːsəbl/',     chinese: '可能的',     sentence: 'Anything is possible.', difficulty: 2, domain: '常用形容词' },
  { id: 'w054', word: 'responsible', phonetic: '/rɪˈspɑːnsəbl/', chinese: '负责的',     sentence: 'Be responsible for your actions.', difficulty: 4, domain: '常用形容词' },
  { id: 'w055', word: 'successful',  phonetic: '/səkˈsesfl/',    chinese: '成功的',     sentence: 'She is a successful writer.', difficulty: 3, domain: '常用形容词' },
  { id: 'w056', word: 'terrible',    phonetic: '/ˈterəbl/',      chinese: '糟糕的',     sentence: 'The weather is terrible today.', difficulty: 2, domain: '常用形容词' },
  { id: 'w057', word: 'valuable',    phonetic: '/ˈvæljuəbl/',    chinese: '有价值的',   sentence: 'This experience is valuable.', difficulty: 3, domain: '常用形容词' },
  { id: 'w058', word: 'wonderful',   phonetic: '/ˈwʌndərfl/',    chinese: '精彩的',     sentence: 'What a wonderful day!', difficulty: 2, domain: '常用形容词' },
  { id: 'w059', word: 'comfortable', phonetic: '/ˈkʌmftəbl/',    chinese: '舒适的',     sentence: 'This bed is very comfortable.', difficulty: 3, domain: '常用形容词' },
  { id: 'w060', word: 'essential',   phonetic: '/ɪˈsenʃl/',      chinese: '本质的',     sentence: 'Sleep is essential for health.', difficulty: 3, domain: '常用形容词' },

  // ── 抽象名词 ──
  { id: 'w061', word: 'ability',     phonetic: '/əˈbɪləti/',     chinese: '能力',       sentence: 'He has the ability to succeed.', difficulty: 3, domain: '抽象名词' },
  { id: 'w062', word: 'advantage',   phonetic: '/ədˈvæntɪdʒ/',   chinese: '优势',       sentence: 'Practice gives you an advantage.', difficulty: 3, domain: '抽象名词' },
  { id: 'w063', word: 'attention',   phonetic: '/əˈtenʃn/',      chinese: '注意',       sentence: 'Pay attention to the details.', difficulty: 3, domain: '抽象名词' },
  { id: 'w064', word: 'challenge',   phonetic: '/ˈtʃælɪndʒ/',    chinese: '挑战',       sentence: 'Life is full of challenges.', difficulty: 3, domain: '抽象名词' },
  { id: 'w065', word: 'condition',   phonetic: '/kənˈdɪʃn/',     chinese: '条件',       sentence: 'Hard work is a condition for success.', difficulty: 3, domain: '抽象名词' },
  { id: 'w066', word: 'difference',  phonetic: '/ˈdɪfrəns/',     chinese: '不同',       sentence: 'There is a big difference.', difficulty: 2, domain: '抽象名词' },
  { id: 'w067', word: 'education',   phonetic: '/ˌedʒuˈkeɪʃn/',  chinese: '教育',       sentence: 'Education changes lives.', difficulty: 3, domain: '抽象名词' },
  { id: 'w068', word: 'experience',  phonetic: '/ɪkˈspɪriəns/',  chinese: '经历',       sentence: 'Travel is a great experience.', difficulty: 3, domain: '抽象名词' },
  { id: 'w069', word: 'freedom',     phonetic: '/ˈfriːdəm/',     chinese: '自由',       sentence: 'Everyone loves freedom.', difficulty: 2, domain: '抽象名词' },
  { id: 'w070', word: 'knowledge',   phonetic: '/ˈnɒlɪdʒ/',      chinese: '知识',       sentence: 'Knowledge is power.', difficulty: 3, domain: '抽象名词' },
  { id: 'w071', word: 'opportunity', phonetic: '/ˌɒpərˈtjuːnəti/', chinese: '机会',     sentence: 'Dont miss this opportunity.', difficulty: 4, domain: '抽象名词' },
  { id: 'w072', word: 'practice',    phonetic: '/ˈpræktɪs/',     chinese: '练习',       sentence: 'Practice makes perfect.', difficulty: 2, domain: '抽象名词' },
  { id: 'w073', word: 'relationship',phonetic: '/rɪˈleɪʃnʃɪp/',  chinese: '关系',       sentence: 'Build good relationships.', difficulty: 4, domain: '抽象名词' },
  { id: 'w074', word: 'situation',   phonetic: '/ˌsɪtʃuˈeɪʃn/',  chinese: '情况',       sentence: 'This is a difficult situation.', difficulty: 3, domain: '抽象名词' },
  { id: 'w075', word: 'tradition',   phonetic: '/trəˈdɪʃn/',     chinese: '传统',       sentence: 'We should keep our traditions.', difficulty: 3, domain: '抽象名词' },
  { id: 'w076', word: 'university',  phonetic: '/ˌjuːnɪˈvɜːrsəti/', chinese: '大学',    sentence: 'He wants to go to university.', difficulty: 3, domain: '抽象名词' },
  { id: 'w077', word: 'volunteer',   phonetic: '/ˌvɒlənˈtɪr/',   chinese: '志愿者',     sentence: 'She works as a volunteer.', difficulty: 3, domain: '抽象名词' },
  { id: 'w078', word: 'adventure',   phonetic: '/ədˈventʃər/',   chinese: '冒险',       sentence: 'Life is an adventure.', difficulty: 3, domain: '抽象名词' },
  { id: 'w079', word: 'community',   phonetic: '/kəˈmjuːnəti/',  chinese: '社区',       sentence: 'Our community is very friendly.', difficulty: 3, domain: '抽象名词' },
  { id: 'w080', word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', chinese: '环境',      sentence: 'Protect the environment.', difficulty: 3, domain: '抽象名词' },

  // ── 高频动词（继续） ──
  { id: 'w081', word: 'appreciate',  phonetic: '/əˈpriːʃieɪt/',  chinese: '感激',       sentence: 'I appreciate your help.', difficulty: 4, domain: '常用动词' },
  { id: 'w082', word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', chinese: '交流',      sentence: 'We communicate every day.', difficulty: 4, domain: '常用动词' },
  { id: 'w083', word: 'concentrate', phonetic: '/ˈkɑːnsntreɪt/', chinese: '集中',       sentence: 'Concentrate on your studies.', difficulty: 4, domain: '常用动词' },
  { id: 'w084', word: 'demonstrate', phonetic: '/ˈdemənstreɪt/', chinese: '展示',       sentence: 'Let me demonstrate how it works.', difficulty: 4, domain: '常用动词' },
  { id: 'w085', word: 'disappear',   phonetic: '/ˌdɪsəˈpɪr/',    chinese: '消失',       sentence: 'The sun disappeared behind clouds.', difficulty: 3, domain: '常用动词' },
  { id: 'w086', word: 'encourage',   phonetic: '/ɪnˈkɜːrɪdʒ/',   chinese: '鼓励',       sentence: 'Teachers encourage students.', difficulty: 3, domain: '常用动词' },
  { id: 'w087', word: 'examine',     phonetic: '/ɪɡˈzæmɪn/',     chinese: '检查',       sentence: 'The doctor examined me.', difficulty: 3, domain: '常用动词' },
  { id: 'w088', word: 'guarantee',   phonetic: '/ˌɡærənˈtiː/',   chinese: '保证',       sentence: 'I cannot guarantee success.', difficulty: 4, domain: '常用动词' },
  { id: 'w089', word: 'identify',    phonetic: '/aɪˈdentɪfaɪ/',  chinese: '识别',       sentence: 'Can you identify the problem?', difficulty: 4, domain: '常用动词' },
  { id: 'w090', word: 'influence',   phonetic: '/ˈɪnfluəns/',    chinese: '影响',       sentence: 'Books can influence our thinking.', difficulty: 3, domain: '常用动词' },
  { id: 'w091', word: 'introduce',   phonetic: '/ˌɪntrəˈduːs/',  chinese: '介绍',       sentence: 'Let me introduce my friend.', difficulty: 3, domain: '常用动词' },
  { id: 'w092', word: 'investigate', phonetic: '/ɪnˈvestɪɡeɪt/', chinese: '调查',       sentence: 'The police are investigating.', difficulty: 4, domain: '常用动词' },
  { id: 'w093', word: 'organize',    phonetic: '/ˈɔːrɡənaɪz/',   chinese: '组织',       sentence: 'We need to organize the event.', difficulty: 3, domain: '常用动词' },
  { id: 'w094', word: 'participate', phonetic: '/pɑːrˈtɪsɪpeɪt/',chinese: '参与',       sentence: 'Everyone should participate.', difficulty: 4, domain: '常用动词' },
  { id: 'w095', word: 'recommend',   phonetic: '/ˌrekəˈmend/',   chinese: '推荐',       sentence: 'I recommend this book.', difficulty: 3, domain: '常用动词' },
  { id: 'w096', word: 'separate',    phonetic: '/ˈsepəreɪt/',    chinese: '分开',       sentence: 'Separate the eggs carefully.', difficulty: 3, domain: '常用动词' },
  { id: 'w097', word: 'struggle',    phonetic: '/ˈstrʌɡl/',      chinese: '挣扎',       sentence: 'He struggled with the problem.', difficulty: 3, domain: '常用动词' },
  { id: 'w098', word: 'translate',   phonetic: '/trænzˈleɪt/',   chinese: '翻译',       sentence: 'Can you translate this sentence?', difficulty: 3, domain: '常用动词' },
  { id: 'w099', word: 'understand',  phonetic: '/ˌʌndərˈstænd/', chinese: '理解',       sentence: 'I understand your feelings.', difficulty: 2, domain: '常用动词' },
  { id: 'w100', word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', chinese: '沟通',      sentence: 'It is important to communicate.', difficulty: 4, domain: '常用动词' },

  // ── 书面语/学术词汇 ──
  { id: 'w101', word: 'academic',    phonetic: '/ˌækəˈdemɪk/',   chinese: '学术的',     sentence: 'She has an academic background.', difficulty: 4, domain: '学术词汇' },
  { id: 'w102', word: 'analysis',    phonetic: '/əˈnæləsɪs/',    chinese: '分析',       sentence: 'We need a full analysis.', difficulty: 4, domain: '学术词汇' },
  { id: 'w103', word: 'approach',    phonetic: '/əˈproʊtʃ/',     chinese: '方法',       sentence: 'Try a different approach.', difficulty: 3, domain: '学术词汇' },
  { id: 'w104', word: 'assess',      phonetic: '/əˈses/',        chinese: '评估',       sentence: 'Assess the situation first.', difficulty: 4, domain: '学术词汇' },
  { id: 'w105', word: 'concept',     phonetic: '/ˈkɑːnsept/',    chinese: '概念',       sentence: 'This is a difficult concept.', difficulty: 3, domain: '学术词汇' },
  { id: 'w106', word: 'conclude',    phonetic: '/kənˈkluːd/',    chinese: '总结',       sentence: 'What can we conclude?', difficulty: 3, domain: '学术词汇' },
  { id: 'w107', word: 'conflict',    phonetic: '/ˈkɑːnflɪkt/',   chinese: '冲突',       sentence: 'Avoid unnecessary conflict.', difficulty: 3, domain: '学术词汇' },
  { id: 'w108', word: 'consequence', phonetic: '/ˈkɑːnsɪkwens/', chinese: '后果',       sentence: 'Every action has consequences.', difficulty: 4, domain: '学术词汇' },
  { id: 'w109', word: 'contribute',  phonetic: '/kənˈtrɪbjuːt/', chinese: '贡献',       sentence: 'Everyone can contribute ideas.', difficulty: 4, domain: '学术词汇' },
  { id: 'w110', word: 'debate',      phonetic: '/dɪˈbeɪt/',      chinese: '辩论',       sentence: 'We had a lively debate.', difficulty: 3, domain: '学术词汇' },
  { id: 'w111', word: 'define',      phonetic: '/dɪˈfaɪn/',      chinese: '定义',       sentence: 'How do you define success?', difficulty: 3, domain: '学术词汇' },
  { id: 'w112', word: 'distinguish', phonetic: '/dɪˈstɪŋɡwɪʃ/',  chinese: '区分',       sentence: 'Can you distinguish them?', difficulty: 4, domain: '学术词汇' },
  { id: 'w113', word: 'evaluate',    phonetic: '/ɪˈvæljueɪt/',   chinese: '评价',       sentence: 'Evaluate the results carefully.', difficulty: 4, domain: '学术词汇' },
  { id: 'w114', word: 'evidence',    phonetic: '/ˈevɪdəns/',     chinese: '证据',       sentence: 'We need more evidence.', difficulty: 3, domain: '学术词汇' },
  { id: 'w115', word: 'hypothesis',  phonetic: '/haɪˈpɑːθəsɪs/', chinese: '假设',       sentence: 'Test your hypothesis.', difficulty: 5, domain: '学术词汇' },
  { id: 'w116', word: 'implement',   phonetic: '/ˈɪmplɪment/',   chinese: '实施',       sentence: 'We need to implement the plan.', difficulty: 4, domain: '学术词汇' },
  { id: 'w117', word: 'interpret',   phonetic: '/ɪnˈtɜːrprɪt/',  chinese: '解释',       sentence: 'Interpret the data carefully.', difficulty: 4, domain: '学术词汇' },
  { id: 'w118', word: 'phenomenon',  phonetic: '/fəˈnɒmɪnən/',   chinese: '现象',       sentence: 'It is a natural phenomenon.', difficulty: 4, domain: '学术词汇' },
  { id: 'w119', word: 'significant', phonetic: '/sɪɡˈnɪfɪkənt/', chinese: '重要的',     sentence: 'This is a significant discovery.', difficulty: 4, domain: '学术词汇' },
  { id: 'w120', word: 'theoretical', phonetic: '/ˌθiːəˈretɪkl/', chinese: '理论的',     sentence: 'It is a theoretical question.', difficulty: 4, domain: '学术词汇' },

  // ── 核心短语/搭配（整词记忆） ──
  { id: 'w121', word: 'together',    phonetic: '/təˈɡeðər/',     chinese: '一起',       sentence: 'Let us work together.', difficulty: 2, domain: '常考短语' },
  { id: 'w122', word: 'already',     phonetic: '/ɔːlˈredi/',     chinese: '已经',       sentence: 'I have already finished.', difficulty: 2, domain: '常考短语' },
  { id: 'w123', word: 'although',    phonetic: '/ɔːlˈðoʊ/',      chinese: '虽然',       sentence: 'Although it rained, we went out.', difficulty: 3, domain: '常考短语' },
  { id: 'w124', word: 'therefore',   phonetic: '/ˈðerfɔːr/',     chinese: '因此',       sentence: 'I think, therefore I am.', difficulty: 3, domain: '常考短语' },
  { id: 'w125', word: 'however',     phonetic: '/haʊˈevər/',     chinese: '然而',       sentence: 'It is cold; however, we went out.', difficulty: 2, domain: '常考短语' },
  { id: 'w126', word: 'although',    phonetic: '/ɔːlˈðoʊ/',      chinese: '尽管',       sentence: 'Although tired, she kept working.', difficulty: 3, domain: '常考短语' },
  { id: 'w127', word: 'immediately', phonetic: '/ɪˈmiːdiətli/',  chinese: '立刻',       sentence: 'Come here immediately!', difficulty: 3, domain: '常考短语' },
  { id: 'w128', word: 'especially',  phonetic: '/ɪˈspeʃəli/',    chinese: '特别',       sentence: 'I love flowers, especially roses.', difficulty: 3, domain: '常考短语' },
  { id: 'w129', word: 'occasionally',phonetic: '/əˈkeɪʒnəli/',   chinese: '偶尔',       sentence: 'We meet occasionally.', difficulty: 4, domain: '常考短语' },
  { id: 'w130', word: 'eventually',  phonetic: '/ɪˈventʃuəli/',  chinese: '最终',       sentence: 'Eventually, we succeeded.', difficulty: 3, domain: '常考短语' },
  { id: 'w131', word: 'absolutely',  phonetic: '/ˈæbsəluːtli/',  chinese: '绝对',       sentence: 'You are absolutely right.', difficulty: 3, domain: '常考短语' },
  { id: 'w132', word: 'fortunately', phonetic: '/ˈfɔːrtʃənətli/',chinese: '幸运的是',   sentence: 'Fortunately, nobody got hurt.', difficulty: 4, domain: '常考短语' },
  { id: 'w133', word: 'unfortunately', phonetic: '/ʌnˈfɔːrtʃənətli/', chinese: '不幸的是', sentence: 'Unfortunately, it rained.', difficulty: 4, domain: '常考短语' },
  { id: 'w134', word: 'represent',   phonetic: '/ˌreprɪˈzent/',  chinese: '代表',       sentence: 'This symbol represents peace.', difficulty: 3, domain: '常考短语' },
  { id: 'w135', word: 'throughout',  phonetic: '/θruːˈaʊt/',     chinese: '贯穿',       sentence: 'It rained throughout the day.', difficulty: 3, domain: '常考短语' },

  // ── 科技/现代词汇 ──
  { id: 'w136', word: 'technology',  phonetic: '/tekˈnɒlədʒi/',  chinese: '技术',       sentence: 'Technology changes fast.', difficulty: 3, domain: '科技词汇' },
  { id: 'w137', word: 'internet',    phonetic: '/ˈɪntərnet/',    chinese: '互联网',     sentence: 'The internet connects the world.', difficulty: 2, domain: '科技词汇' },
  { id: 'w138', word: 'computer',    phonetic: '/kəmˈpjuːtər/',  chinese: '计算机',     sentence: 'Computers are everywhere.', difficulty: 2, domain: '科技词汇' },
  { id: 'w139', word: 'software',    phonetic: '/ˈsɒftwer/',     chinese: '软件',       sentence: 'Install the software first.', difficulty: 3, domain: '科技词汇' },
  { id: 'w140', word: 'database',    phonetic: '/ˈdeɪtəbeɪs/',   chinese: '数据库',     sentence: 'Store data in a database.', difficulty: 3, domain: '科技词汇' },
  { id: 'w141', word: 'algorithm',   phonetic: '/ˈælɡərɪðəm/',   chinese: '算法',       sentence: 'This algorithm is very fast.', difficulty: 4, domain: '科技词汇' },
  { id: 'w142', word: 'artificial',  phonetic: '/ˌɑːrtɪˈfɪʃl/',  chinese: '人工的',     sentence: 'Artificial intelligence is growing.', difficulty: 4, domain: '科技词汇' },
  { id: 'w143', word: 'digital',     phonetic: '/ˈdɪdʒɪtl/',     chinese: '数字的',     sentence: 'We live in a digital world.', difficulty: 3, domain: '科技词汇' },
  { id: 'w144', word: 'network',     phonetic: '/ˈnetwɜːrk/',    chinese: '网络',       sentence: 'The network is down.', difficulty: 2, domain: '科技词汇' },
  { id: 'w145', word: 'security',    phonetic: '/sɪˈkjʊrəti/',   chinese: '安全',       sentence: 'Online security is important.', difficulty: 3, domain: '科技词汇' },
  { id: 'w146', word: 'innovation',  phonetic: '/ˌɪnəˈveɪʃn/',   chinese: '创新',       sentence: 'Innovation drives progress.', difficulty: 4, domain: '科技词汇' },
  { id: 'w147', word: 'platform',    phonetic: '/ˈplætfɔːrm/',   chinese: '平台',       sentence: 'This is a great learning platform.', difficulty: 3, domain: '科技词汇' },
  { id: 'w148', word: 'program',     phonetic: '/ˈproʊɡræm/',    chinese: '程序',       sentence: 'Write a computer program.', difficulty: 2, domain: '科技词汇' },
  { id: 'w149', word: 'data',        phonetic: '/ˈdeɪtə/',       chinese: '数据',       sentence: 'We need more data.', difficulty: 2, domain: '科技词汇' },
  { id: 'w150', word: 'function',    phonetic: '/ˈfʌŋkʃn/',      chinese: '功能',       sentence: 'What is the function of this button?', difficulty: 3, domain: '科技词汇' },

  // ── 进阶/高考高频 ──
  { id: 'w151', word: 'accommodate', phonetic: '/əˈkɑːmədeɪt/',  chinese: '容纳',       sentence: 'The room can accommodate 50 people.', difficulty: 5, domain: '进阶词汇' },
  { id: 'w152', word: 'accompany',   phonetic: '/əˈkʌmpəni/',    chinese: '陪伴',       sentence: 'I will accompany you.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w153', word: 'accomplish',  phonetic: '/əˈkɑːmplɪʃ/',   chinese: '完成',       sentence: 'We accomplished our mission.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w154', word: 'accurate',    phonetic: '/ˈækjərət/',     chinese: '准确的',     sentence: 'The information is accurate.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w155', word: 'announce',    phonetic: '/əˈnaʊns/',      chinese: '宣布',       sentence: 'They announced the winner.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w156', word: 'appropriate', phonetic: '/əˈproʊpriət/',  chinese: '适当的',     sentence: 'Wear appropriate clothing.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w157', word: 'assume',      phonetic: '/əˈsuːm/',       chinese: '假设',       sentence: 'I assume you are correct.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w158', word: 'atmosphere',  phonetic: '/ˈætməsfɪr/',    chinese: '气氛',       sentence: 'The atmosphere was tense.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w159', word: 'available',   phonetic: '/əˈveɪləbl/',    chinese: '可用的',     sentence: 'Is this seat available?', difficulty: 3, domain: '进阶词汇' },
  { id: 'w160', word: 'awkward',     phonetic: '/ˈɔːkwərd/',     chinese: '尴尬的',     sentence: 'It was an awkward silence.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w161', word: 'balance',     phonetic: '/ˈbæləns/',      chinese: '平衡',       sentence: 'Keep a balance of work and rest.', difficulty: 2, domain: '进阶词汇' },
  { id: 'w162', word: 'benefit',     phonetic: '/ˈbenɪfɪt/',     chinese: '益处',       sentence: 'Exercise has many benefits.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w163', word: 'campaign',    phonetic: '/kæmˈpeɪn/',     chinese: '运动',       sentence: 'The campaign was successful.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w164', word: 'circumstance',phonetic: '/ˈsɜːrkəmstæns/',chinese: '环境',       sentence: 'Under the circumstances, we must be careful.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w165', word: 'complain',    phonetic: '/kəmˈpleɪn/',    chinese: '抱怨',       sentence: 'Dont complain about everything.', difficulty: 2, domain: '进阶词汇' },
  { id: 'w166', word: 'confident',   phonetic: '/ˈkɑːnfɪdənt/',  chinese: '自信的',     sentence: 'Be confident in yourself.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w167', word: 'conscious',   phonetic: '/ˈkɑːnʃəs/',     chinese: '有意识的',   sentence: 'Be conscious of your actions.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w168', word: 'curious',     phonetic: '/ˈkjʊriəs/',     chinese: '好奇的',     sentence: 'Children are naturally curious.', difficulty: 2, domain: '进阶词汇' },
  { id: 'w169', word: 'desperate',   phonetic: '/ˈdespərət/',    chinese: '绝望的',     sentence: 'He was desperate for help.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w170', word: 'determined',  phonetic: '/dɪˈtɜːrmɪnd/',  chinese: '坚定的',     sentence: 'She is determined to succeed.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w171', word: 'discipline',  phonetic: '/ˈdɪsəplɪn/',    chinese: '纪律',       sentence: 'Discipline is the key to success.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w172', word: 'discovery',   phonetic: '/dɪˈskʌvəri/',   chinese: '发现',       sentence: 'This is an important discovery.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w173', word: 'embarrassed', phonetic: '/ɪmˈbærəst/',    chinese: '尴尬的',     sentence: 'I felt embarrassed.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w174', word: 'emotion',     phonetic: '/ɪˈmoʊʃn/',      chinese: '情感',       sentence: 'She showed no emotion.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w175', word: 'enthusiasm',  phonetic: '/ɪnˈθuːziæzəm/', chinese: '热情',       sentence: 'She is full of enthusiasm.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w176', word: 'establish',   phonetic: '/ɪˈstæblɪʃ/',    chinese: '建立',       sentence: 'They established a new company.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w177', word: 'explore',     phonetic: '/ɪkˈsplɔːr/',    chinese: '探索',       sentence: 'We explored the forest.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w178', word: 'fascinating', phonetic: '/ˈfæsɪneɪtɪŋ/',  chinese: '迷人的',     sentence: 'The story is fascinating.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w179', word: 'guilty',      phonetic: '/ˈɡɪlti/',       chinese: '内疚的',     sentence: 'I feel guilty about it.', difficulty: 2, domain: '进阶词汇' },
  { id: 'w180', word: 'independent', phonetic: '/ˌɪndɪˈpendənt/',chinese: '独立的',     sentence: 'She is very independent.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w181', word: 'jealous',     phonetic: '/ˈdʒeləs/',      chinese: '嫉妒的',     sentence: 'Dont be jealous of others.', difficulty: 2, domain: '进阶词汇' },
  { id: 'w182', word: 'literature',  phonetic: '/ˈlɪtrətʃər/',   chinese: '文学',       sentence: 'I love English literature.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w183', word: 'mischievous', phonetic: '/ˈmɪstʃɪvəs/',   chinese: '淘气的',     sentence: 'The mischievous boy hid my keys.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w184', word: 'necessary',   phonetic: '/ˈnesəseri/',    chinese: '必要的',     sentence: 'Food is necessary for life.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w185', word: 'negotiate',   phonetic: '/nɪˈɡoʊʃieɪt/',  chinese: '谈判',       sentence: 'They need to negotiate a deal.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w186', word: 'obvious',     phonetic: '/ˈɑːbviəs/',     chinese: '明显的',     sentence: 'The answer is obvious.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w187', word: 'occupy',      phonetic: '/ˈɑːkjupaɪ/',    chinese: '占据',       sentence: 'The seat is occupied.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w188', word: 'persuade',    phonetic: '/pərˈsweɪd/',    chinese: '说服',       sentence: 'I persuaded him to come.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w189', word: 'possess',     phonetic: '/pəˈzes/',       chinese: '拥有',       sentence: 'She possesses great talent.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w190', word: 'prejudice',   phonetic: '/ˈpredʒudɪs/',   chinese: '偏见',       sentence: 'Prejudice divides people.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w191', word: 'privilege',   phonetic: '/ˈprɪvəlɪdʒ/',   chinese: '特权',       sentence: 'Education is a privilege.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w192', word: 'recognize',   phonetic: '/ˈrekəɡnaɪz/',   chinese: '认出',       sentence: 'I recognized her immediately.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w193', word: 'reluctant',   phonetic: '/rɪˈlʌktənt/',   chinese: '不情愿的',   sentence: 'He was reluctant to leave.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w194', word: 'sacrifice',   phonetic: '/ˈsækrɪfaɪs/',   chinese: '牺牲',       sentence: 'Parents sacrifice for their children.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w195', word: 'sufficient',  phonetic: '/səˈfɪʃnt/',     chinese: '充足的',     sentence: 'We have sufficient time.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w196', word: 'sympathy',    phonetic: '/ˈsɪmpəθi/',     chinese: '同情',       sentence: 'I have sympathy for her.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w197', word: 'temporary',   phonetic: '/ˈtempəreri/',   chinese: '临时的',     sentence: 'This is only temporary.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w198', word: 'thorough',    phonetic: '/ˈθɜːroʊ/',      chinese: '彻底的',     sentence: 'Do a thorough check.', difficulty: 3, domain: '进阶词汇' },
  { id: 'w199', word: 'tremendous',  phonetic: '/trəˈmendəs/',   chinese: '巨大的',     sentence: 'We made tremendous progress.', difficulty: 4, domain: '进阶词汇' },
  { id: 'w200', word: 'vulnerable',  phonetic: '/ˈvʌlnərəbl/',   chinese: '脆弱的',     sentence: 'Children are vulnerable.', difficulty: 4, domain: '进阶词汇' },
];
